let suggestions = [
"The Great Gatsby",
"F. Scott Fitzgerald",
"1925",
"To Kill a Mockingbird",
"Harper Lee	1960",
"1984",
"George Orwell",
"1949",
"Pride and Prejudice",
"Jane Austen",
"1813",
"The Catcher in the Rye",
"J.D. Salinger",
"1951",
"The Lord of the Rings",
"J.R.R. Tolkien",
"1954",
"Harry Potter and the Sorcerer's Stone",
"J.K. Rowling",
"1997",
"Brave New World",
"Aldous Huxley",
"1932",
"The Hobbit",
"J.R.R. Tolkien",
"1937",
"Crime and Punishment",
"Fyodor Dostoevsky",
"1866",        	
"The Alchemist",
"Paulo Coelho",
"1988",
];
